on:
  push:
    branches:
    - "main"

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        nimversion:
          - '2.x'

        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        path: "figuro/"
    - uses: iffy/install-nim@v4
      with:
        version: ${{ matrix.nimversion }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Atlas
      run: |
        nim -v
        nimble -v
        nimble install 'https://github.com/nim-lang/atlas@#78b6814a05ec1b18eef388c7336f583eb6e9993f'

    - name: Cache packages
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-${{ hashFiles('figuro/atlas.lock') }}

    - name: Install Deps
      run: |
        # sync deps
        atlas replay --cfgHere --ignoreUrls atlas.lock
        cat nim.cfg

    - name: Build Tests
      run: |
        nim test
